version: "2"

services:
  zookeeper1:
    image: zkpv1:latest
    hostname: zookeeper1
    container_name: zookeeper1 
    ports:
      - "2181:2181"
    networks:
      - khadoop
  kafka1:
    image: kfkav1:latest
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9192:9092"
    networks:
      - khadoop
  kafka2:
    image: kfkav1:latest
    hostname: kafka2
    container_name: kafka2
    ports:
      - "9292:9092"
    networks:
      - khadoop

networks:
  khadoop:
